services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    ports:
      - 127.0.0.1:8123:8123 #optional
